<?php

function rssmodule_block_info(){
    $blocks['rssblock'] = array(
        'info' => "RSS Show module",

    );
    return $blocks;
}

function load_rss($result = 'item'){
    $rss_url = "http://partners.userland.com/nytRss/nytHomepage.xml";
    $rss= simplexml_load_file($rss_url);
    $data =  $rss->channel->$result;
    return $data;
}

function rssmodule_block_view($delta = ''){
    switch ($delta){
        case 'rssblock':
            $block['subject'] = load_rss('title');
            $block['content'] = rssblock_view(10);
            break;
    }
    return $block;
}

function rssblock_view($j){
    $res = load_rss();

    for ($i = 0; $i < $j; $i++) {
        $item[] = array(
            'title' => $res[$i]->title,
            'link' => $res[$i]->link,
            'description' => $res[$i]->description,
        );
    }

    return theme('rssblock', array('item' => $item));
}

function rssmodule_theme(){
    return array(
        'rssblock' => array(
            'template' => 'rssblock',
            'variables' => array ('item' => array()),
        )
    );
}

function rssmodule_menu(){
    $menu['rss/%rss'] = array(
        'title callback' => 'rss_title_callback',
        'title arguments' => array(1),
        'page callback' => 'rss_page',
        'page arguments' => array(1),
        'access callback' => 'access_rss'
    );
    $menu['rss'] = array(
        'page callback' => 'rss_p',
        'access callback' => 'access_rss'
    );
    return $menu;
}

function rss_load($param){
    $res = load_rss();
    $content = $res[$param-1];
    if (!$content || $param == 0){
        return false;
    }
    else {
        return $content;
    }
}

function rss_title_callback($param){

    return "$param->title";
}

function rss_page($param){
    return "<pre>$param->description</pre>";
}

function access_rss(){
    return true;
}

function rss_p(){
    $res = load_rss();
    $i = 1;
    while ($content = $res[$i]) {
        $i++;
    }
    return rssblock_view($i);
}