<?php

function rssmodule_block_info(){
    $blocks['rssblock'] = array(
        'info' => "RSS Show module",

    );
    return $blocks;
}

function load_rss($result = 'item'){
    $rss_url = variable_get('url_rss');
    $rss= simplexml_load_file($rss_url);
    $data =  $rss->channel->$result;
    return $data;
}

function rssmodule_block_view($delta = ''){
    switch ($delta){
        case 'rssblock':
            $block['subject'] = load_rss('title');
            $block['content'] = rssblock_view(10);
            break;
    }
    return $block;
}

function rssblock_view($j){
    $res = load_rss();

    for ($i = 0; $i < $j; $i++) {
        $item[] = array(
            'title' => $res[$i]->title,
            'link' => $res[$i]->link,
            'description' => $res[$i]->description,
        );
    }

    return theme('rssblock', array('item' => $item));
}

function rssmodule_theme(){
    return array(
        'rssblock' => array(
            'template' => 'rssblock',
            'variables' => array ('item' => array()),
        )
    );
}

function rssmodule_menu(){
    $menu['rss/%rss'] = array(
        'title callback' => 'rss_title_callback',
        'title arguments' => array(1),
        'page callback' => 'rss_page',
        'page arguments' => array(1),
        'access callback' => 'access_rss'
    );
    $menu['rss'] = array(
        'page callback' => 'rss_p',
        'access callback' => 'access_rss'
    );
    $menu['admin/settings/url_rss'] = array(
        'title'=>'RSS module settings',
        'description' => 'Description of your RSS settings page',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('rssmodule_admin'),
        'access arguments' => array('administer rssmodule settings'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $menu;
}

function rss_load($param){
    $res = load_rss();
    $content = $res[$param-1];
    if (!$content || $param == 0){
        return false;
    }
    else {
        return $content;
    }
}

function rss_title_callback($param){

    return "$param->title";
}

function rss_page($param){
    return "<pre>$param->description</pre>";
}

function access_rss(){
    return true;
}

function rss_p(){
    $res = load_rss();
    $i = 1;
    while ($content = $res[$i]) {
        $i++;
    }
    return rssblock_view($i);
}

/*********Настройки модуля************/

function rssmodule_admin(){
    $form = array();
    $form['url_rss'] = array(
        '#type'=>'textfield',
        '#title'=>t('URL of RSS'),
        '#default_value'=>variable_get('url_rss','http://partners.userland.com/nytRss/nytHomepage.xml'),
        '#size'=>100,
        '#maxlength'=>255,
        '#description'=>t("Type your RRS feed"),
        '#required'=>TRUE,
    );
    return system_settings_form($form);
}

